### ISSUE TITLE
Could the mod not be dependant on classicitem by thinkinvis.

### ISSUE THREAD

**Issue by benjdidj** [cheeeeeeeeeen/RoR2-ClassicItems#30]
I don't use classic item by thinkinvis anymore for many reasons.(bugs, Op stuff,...) I know i can disable every aspect of the mod in cfgs but they load anyway sort of. 
In any case Thx for the mod

**Comment by cheeeeeeeeeen** [comment]
I tried, but I want to dedicate my thanks to that mod by requiring it, so that people will take notice of where it came from and where it was inspired from.

On a technical side, there is an issue. Re-implementing the item cards, for example. There were a lot of things used from ThinkInvis that i did not need implementing if i depended on it.

It's not easy to simply re add his code. I would need to detect his hooks and what not, which is kind of painful to do.

**Comment by benjdidj** [comment]
I understand thinkinvis mod is really cool. Should have been a lot of work.
Thx for answering.
